# Generated by Django 3.2.20 on 2023-07-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_User', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=60)),
                ('senha', models.CharField(max_length=30)),
            ],
        ),
    ]
